import { Doctor, HospitalKnowledgeItem, PatientMemory, MedicalRecord } from './types';

export const DEMO_HOSPITAL_NAME = 'City Medical Center';
export const DEMO_HOSPITAL_ID = 'hospital_city';

export const DEMO_DOCTORS: Doctor[] = [
  {
    id: 'doc-1',
    hospital_id: 'hospital_city',
    name: 'Dr. Amit Sharma',
    specialty: 'Orthopedic',
    hospital: DEMO_HOSPITAL_NAME,
    experience: '12 Years',
    languages: ['Hindi', 'English'],
    location: 'Orthopedic Department • Wing B',
    rating: 4.8,
    available_slots: {
      today: ['3:30 PM', '5:00 PM', '6:30 PM'],
      tomorrow: ['10:30 AM', '1:00 PM', '4:00 PM'],
    },
    consultation_fee: '₹800',
  },
  {
    id: 'doc-2',
    hospital_id: 'hospital_city',
    name: 'Dr. Neha Singh',
    specialty: 'Dermatologist',
    hospital: DEMO_HOSPITAL_NAME,
    experience: '8 Years',
    languages: ['Hindi', 'English'],
    location: 'Dermatology Wing • Floor 2',
    rating: 4.7,
    available_slots: {
      today: ['11:30 AM', '2:30 PM', '5:30 PM'],
      tomorrow: ['10:00 AM', '1:30 PM', '4:30 PM'],
    },
    consultation_fee: '₹700',
  },
  {
    id: 'doc-3',
    hospital_id: 'hospital_city',
    name: 'Dr. Pooja Verma',
    specialty: 'Cardiologist',
    hospital: DEMO_HOSPITAL_NAME,
    experience: '15 Years',
    languages: ['Hindi', 'English'],
    location: 'Cardiology Block • Wing A',
    rating: 4.9,
    available_slots: {
      today: ['1:30 PM', '4:00 PM'],
      tomorrow: ['11:00 AM', '2:30 PM', '5:00 PM'],
    },
    consultation_fee: '₹1200',
  },
  {
    id: 'doc-4',
    hospital_id: 'hospital_city',
    name: 'Dr. Rohit Gupta',
    specialty: 'General Physician',
    hospital: DEMO_HOSPITAL_NAME,
    experience: '10 Years',
    languages: ['Hindi', 'English'],
    location: 'OPD Building • Cabin 4',
    rating: 4.6,
    available_slots: {
      today: ['10:30 AM', '1:00 PM', '6:00 PM'],
      tomorrow: ['9:30 AM', '12:30 PM', '4:30 PM'],
    },
    consultation_fee: '₹500',
  },
  {
    id: 'doc-5',
    hospital_id: 'hospital_city',
    name: 'Dr. Arjun Mehta',
    specialty: 'Pediatrician',
    hospital: DEMO_HOSPITAL_NAME,
    experience: '11 Years',
    languages: ['Hindi', 'English'],
    location: 'Child Care Wing • Floor 1',
    rating: 4.8,
    available_slots: {
      today: ['2:00 PM', '4:30 PM'],
      tomorrow: ['10:00 AM', '1:30 PM', '5:00 PM'],
    },
    consultation_fee: '₹650',
  },
  {
    id: 'doc-6',
    hospital_id: 'hospital_city',
    name: 'Dr. Kavya Malhotra',
    specialty: 'Gynecologist',
    hospital: DEMO_HOSPITAL_NAME,
    experience: '13 Years',
    languages: ['Hindi', 'English'],
    location: 'Women Health Center • Wing C',
    rating: 4.9,
    available_slots: {
      today: [],
      tomorrow: ['10:00 AM', '2:00 PM', '4:30 PM'],
    },
    consultation_fee: '₹900',
  },
  {
    id: 'doc-7',
    hospital_id: 'hospital_city',
    name: 'Dr. Sameer Khanna',
    specialty: 'ENT Specialist',
    hospital: DEMO_HOSPITAL_NAME,
    experience: '9 Years',
    languages: ['Hindi', 'English'],
    location: 'ENT Clinic • Cabin 8',
    rating: 4.7,
    available_slots: {
      today: ['1:00 PM', '5:30 PM'],
      tomorrow: ['9:30 AM', '2:00 PM'],
    },
    consultation_fee: '₹600',
  },
  {
    id: 'doc-8',
    hospital_id: 'hospital_city',
    name: 'Dr. Ritu Bansal',
    specialty: 'Ophthalmologist',
    hospital: DEMO_HOSPITAL_NAME,
    experience: '14 Years',
    languages: ['Hindi', 'English'],
    location: 'Eye Care Unit • Floor 3',
    rating: 4.8,
    available_slots: {
      today: ['12:30 PM', '4:00 PM'],
      tomorrow: ['10:30 AM', '1:00 PM', '4:30 PM'],
    },
    consultation_fee: '₹750',
  },
  {
    id: 'doc-9',
    hospital_id: 'hospital_city',
    name: 'Dr. Vikas Patel',
    specialty: 'Dentist',
    hospital: DEMO_HOSPITAL_NAME,
    experience: '10 Years',
    languages: ['Hindi', 'English'],
    location: 'Dental Clinic • Cabin 12',
    rating: 4.6,
    available_slots: {
      today: ['11:30 AM', '3:30 PM'],
      tomorrow: ['9:00 AM', '12:00 PM', '5:30 PM'],
    },
    consultation_fee: '₹500',
  },
  {
    id: 'doc-10',
    hospital_id: 'hospital_city',
    name: 'Dr. Tanya Kapoor',
    specialty: 'Gastroenterologist',
    hospital: DEMO_HOSPITAL_NAME,
    experience: '12 Years',
    languages: ['Hindi', 'English'],
    location: 'Gastroenterology Wing • Floor 4',
    rating: 4.8,
    available_slots: {
      today: ['2:30 PM', '6:30 PM'],
      tomorrow: ['10:00 AM', '3:00 PM'],
    },
    consultation_fee: '₹1000',
  },
];

export const DEMO_HOSPITAL_KNOWLEDGE: HospitalKnowledgeItem[] = [
  {
    id: 'hk-1',
    hospital_id: 'hospital_city',
    category: 'specialty_map',
    title: 'Knee Pain, Joint Pain, Leg Joint Pain, Back Pain -> Orthopedic Specialist Dr. Amit Sharma',
    content: 'For knee pain, joint pain, leg joint pain, back pain, or orthopedic consultation, consult Orthopedic Specialist Dr. Amit Sharma.',
    content_hi: 'घुटने के दर्द, जोड़ों के दर्द या पीठ दर्द के लिए ऑर्थोपेडिक विशेषज्ञ डॉ. अमित शर्मा से परामर्श लें।',
    keywords: ['knee pain', 'joint pain', 'leg joint pain', 'back pain', 'orthopedic', 'घुटने', 'दर्द', 'हड्डी'],
  },
  {
    id: 'hk-2',
    hospital_id: 'hospital_city',
    category: 'hours',
    title: 'Clinic Operating Hours',
    content: 'The clinic is open today from 9 AM until 8 PM.',
    content_hi: 'क्लीनिक आज सुबह 9 बजे से रात 8 बजे तक खुला है।',
    keywords: ['close', 'timing', 'time', 'hours', 'open', 'समय', 'बंद'],
  },
];

export const INITIAL_PATIENT_MEMORY: PatientMemory = {
  id: 'pat-01',
  patient_name: '',
  preferred_language: 'en',
  previous_visit: {
    doctor: 'Dr. Amit Sharma',
    specialty: 'Orthopedic',
    date: '02 August 2026',
  },
  recent_prescription: {
    medicine: 'Paracetamol 500mg',
    dosage: '1 tablet twice daily',
    instructions: 'After food for knee joint discomfort.',
    instructions_hi: 'खाने के बाद लें।',
  },
  active_appointment: undefined,
  history_logs: [
    'Patient recorded knee discomfort on 02 August 2026.',
  ],
};

export const INITIAL_MEDICAL_RECORDS: MedicalRecord[] = [
  {
    id: 'rec-1',
    title: 'Orthopedic Consultation Summary',
    title_hi: 'ऑर्थोपेडिक परामर्श सारांश',
    date: '02 August 2026',
    type: 'Visit Summary',
    doctor: 'Dr. Amit Sharma',
    hospital: DEMO_HOSPITAL_NAME,
    summary: 'Diagnosis: Mild Knee Strain. Advised warm compression & mild rest.',
    summary_hi: 'निदान: घुटने में हल्की मोच। आराम की सलाह दी गई।',
    details: [
      'Warm Compression — Apply twice daily',
      'Avoid strenuous leg exercises',
    ],
  },
];
